### ISSUE TITLE
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by mahendhar9** [producthunt/producthunt-api#139]
Hi. 
I am requesting a client level token from this endpoint  [/v1/oauth/token](https://api.producthunt.com/v1/docs/oauth_client_only_authentication/oauth_token_ask_for_client_level_token).

But I get the following error:
`Failed to load https://api.producthunt.com/v1/oauth/token: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://null.jsbin.com' is therefore not allowed access.`

This issue was referenced [here too](https://github.com/producthunt/producthunt-api/issues/70). But there was no solution.

I have tried sending the request from localhost, surge.sh and jsbin. The same error everywhere.

You can try sending a request from this [jsbin](https://jsbin.com/gexixog/1/edit?html,js,output).

Thanks in advance!

**Comment by cms5x** [comment]
@mahendhar9 If you are still having the issue, can you paste an example of your request (without your app key or id of course)? 
Make sure you included the Accept, Content-Type, and Host headers. And Make sure your body has client_id, client_secret, and grant_type as per the link to the docs.

**Comment by Thlayli** [comment]
According to the CORS documentation, any requests that set the content-type to application/json will be restricted to preflight and converted from POST to OPTIONS. This causes the TOKEN request to have a null response. In order to POST and receive a token, CORS would have to return a "Access-Control-Allow-Origin: *" header in the response to the OPTION request. Because no such policy exists, any client-only authentication requests fail.

I've tested this behavior in Firefox, Chrome, Edge and IE11. The jsbin example above illustrates it simply, although I have the problem even when using an Angular OAuth library.

The simplest solution seems to be allowing token requests in text/plain or application/x-www-form-urlencoded. Currently I receive errors when passing the required params in any format other than JSON.

**Comment by daividh** [comment]
Same here. See https://jsfiddle.net/mf6euso0/
Is there any solution or workaround ?

**Comment by dhruvparmar372** [comment]
@mahendhar9 the CORS issue has been fixed in the new V2 API powered by GraphQL. 
Closing this issue as V1 API is deprecated and will be out of support. Refer to V2 API [docs](https://api.producthunt.com/v2/docs) for more details.
