### ISSUE TITLE
Question about createdAt/featuredAt dates

### ISSUE THREAD

**Issue by muratsu** [producthunt/producthunt-api#168]
Given the following query:
```
query GetPosts($before: DateTime, $after: DateTime)
{
  posts(postedBefore:$before, postedAfter:$after, order: RANKING) {
    edges {
      node {
        id,
        name,
        tagline,
        slug,
        createdAt,
        featuredAt
      }
    }
  }
}
```
and the variables:
```
{
  "before": "2019-08-21T07:00:00Z",
  "after": "2019-08-20T07:00:00Z"
}
```

The API is returning 

```
{
  "data": {
    "posts": {
      "edges": [
        {
          "node": {
            "id": "165087",
            "name": "SimpleID",
            "tagline": "Add decentralized auth and storage to your app in 10 minutes",
            "slug": "simpleid",
            "createdAt": "2019-08-21T07:23:26Z",
            "featuredAt": "2019-08-21T07:23:26Z"
          }
        },
        {
          "node": {
            "id": "165101",
            "name": "Nudge for Prototypes",
            "tagline": "Catch usability issues and design mistakes pre-deployment.",
            "slug": "nudge-for-prototypes",
            "createdAt": "2019-08-21T07:00:00Z",
            "featuredAt": "2019-08-21T07:00:00Z"
          }
        },
....
```

Note that createdAt time is a later date compared to the before date provided in the graphql query. Not sure what's going on, any help is appreciated.

**Comment by dhruvparmar372** [comment]
Hey @muratsu, thank you for reporting the issue. We had a bug with wrong `created_at` value being sent via the API. It is patched now and you should see correct results in the API. 

By default `postedBefore` & `postedAfter` will filter posts on `created_at` value, incase you want to fetch only posts that were featured you can pass additional `featured: true` to the connection. Consequently posts will be filtered on `featured_at` value instead of `created_at`.
