### ISSUE TITLE
Reading notifications

### ISSUE THREAD

**Issue by DmitryTsepelev** [producthunt/producthunt-api#260]
Hi!

I'm trying to set up a small app that fetches unread notifications from my PH profile.

I tried to do it using V2 GraphQL API, but failed: I see you guys use `ViewerNotificationsLastSeenUpdate` mutation, which is not available with the public scope.

I tried to switch to the V1 REST API, but somehow it returns me an empty list, but I have one unread notification in my profile:

```ruby
HTTParty.get(
  "https://api.producthunt.com/v1/notifications?search[type]=all&per_page=10",
  headers: {
    Accept: "application/json",
    "Content-Type": "application/json",
    Authorization: "Bearer my_token",
    Host: "api.producthunt.com"
  },
)
```

Is V1 still maintained? What am I missing and what's the best way to get notifications?

**Comment by RStankov** [comment]
Hey, V1 is not maintained anymore. The notifications that are returned by V1 are our notifications from 2 rewrites ago and this is the reason it returns an empty array.

We don't expose notifications at the moment, because we are still not happy with their structure and re-vamp them often. Having them exposed in API will constraint us how we can structure them or we will constantly break API contract.

**Comment by unamashana** [comment]
Hey @RStankov! Can we help you with this? I co-founded MagicBell.com and would love to chat with you, or another team member on how we can offer in-app, web-push, email notifications, all with an API that you can offer to your customers.
