### ISSUE TITLE
E-tag per session

### ISSUE THREAD

**Issue by NikolaDespotoski** [producthunt/producthunt-api#39]
Hi,

Does each request at different paths should have different E-tag hash? Is/can one be shared across all requests?

Thanks

**Comment by mscoutermarsh** [comment]
E-Tag is unique per path and is generated based on the content returned.

If you make the same request twice & the content has not changed. The same e-tag will be returned.

In your requests, if you provide the `If-None-Match` header, with the E-Tag, we'll return a `304` if the content has not changed since your last request, making the request faster since we do not need to generate a response.

**Comment by mscoutermarsh** [comment]
An example of this can be seen here: https://api.producthunt.com/v1/docs/example_performance_tips/use_the_e-tag_http_header

**Comment by NikolaDespotoski** [comment]
Awsome. Thanks.
