### ISSUE TITLE
Product Hunt Authorisation Appearance

### ISSUE THREAD

**Issue by edmoyse** [producthunt/producthunt-api#53]
We've been beta testing a new app that authorises through PH - but our users have found it worrying as they're not quite sure what it is or what it's going to do.  It certainly doesn't look very Product Hunt-esque (which is beautifully designed), so I'd love it if you could change that please :)

Specifically, I think it'd help a lot to make authorisation more similar to Twitter:

1. Show the user's Product Hunt profile (pic + name)
2. Change the "Authorization Required" text to "Sign in With Product Hunt"
3. More obvious Product Hunt logo
4. Styling should reflect the rest of Product Hunt (e.g. buttons)

Thanks!
Ed

**Comment by lfittl** [comment]
Thanks for reporting this - you are correct, that page is indeed not that good looking (its the default design from our authorization framework).

We can't give an ETA on this issue, since its not a super high priority - but we'll see if we can fit in a slight design refresh so the UX feels a bit better.

I'll update this issue when we've made progress - thanks for your patience :)

**Comment by andreasklinger** [comment]
Untouched for longer time - Archiving
