### ISSUE TITLE
Notification Id is saved to 0

### ISSUE THREAD

**Issue by sahilsarpal15** [producthunt/producthunt-api#74]
It seems that id of that notification is save to 0 for every notification while fetching all notifications. Can you guys suggestt me a way to add checkpoint while fetching all notifcations. like previously there were "?newer=notificationId". any suggestion would be helpful for me.

**Comment by RStankov** [comment]
Hi, 

We had changed our notification infrastructure. Now our notifications don't have meaningful ids. Because of this `/notifications` endpoint doesn't support `newer` / `older` yet. Due to performance reasons we limit the number of fetched notifications to `50`. We will be working on some improvements regarding notifications in the near future.

**Comment by sahilsarpal15** [comment]
hi,
Can you suggest me a way to fetch notifications after a particular checkpoint ?

**Comment by RStankov** [comment]
Unfortunately at this moment we don't provide this functionality.
