### ISSUE TITLE
Fetch Notifications has no checkpoint

### ISSUE THREAD

**Issue by sahilsarpal15** [producthunt/producthunt-api#75]
I m not able to fetch notifications and not able to set checkpoint in the method. Like before i send last_notification_id as parameters , but now this is not working . Also you are sending id as 0 in your notification payload.

**Comment by RStankov** [comment]
Hi, 

We don't support fetching notifications from a checkpoint point at this moment. The API returns only up to `50` notifications by `/v1/notifications?per_page=50`. 

The notification objects don't have `id` anymore, because of this `last_notification_id`, `older` and `newer` are no longer active.
