### ISSUE TITLE
ProductHunt API access to Facebook info

### ISSUE THREAD

**Issue by StephanKl** [producthunt/producthunt-api#83]
I am accessing the user profile through the ProductHunt API but realized that I am not seeing any information about the Facebook account the user used when signing up.

This is different to the twitter information shown when the user signed up with Twitter.

Are you planning to add this information? It helps to understand who the people are who upvoted my product.

**Comment by lfittl** [comment]
Thanks for the report, we'd love to add it - however:

With Twitter we can provide "twitter_username", since thats a public information that is the same for you and me.

With Facebook however, there is no public URL or username that we have. The only thing we have is the user ID, which since newer Graph API releases is keyed to the app (i.e. you'll get a different one for the same user), so it doesn't help you.

So unfortunately, unless I'm missing something, we can't support this. 😕

**Comment by StephanKl** [comment]
Indeed :(

I just did a quick test via Javascript login (https://developers.facebook.com/docs/facebook-login/web). Looks like apps created after a certain date only get the ID that's keyed to the app, while older apps still get the FB id of the user.
