### ISSUE TITLE
Problem to generate API token

### ISSUE THREAD

**Issue by Vellieuxc** [producthunt/producthunt-api#90]
Hi,

Sorry to bother you!
It seems that the authentication and the token generation for the Product API are no more working. For instance the link 'API dashboard' is leading to an error message
![api product hunt](https://cloud.githubusercontent.com/assets/12086328/14714304/bf7dd298-07f9-11e6-9d8f-0597c5202beb.png)
. The same thing happen when I try to send a token request.
Do you know what happened and when it will be fixed?

Thanks a lot!
Clement

PI

**Comment by mscoutermarsh** [comment]
Hello :)

Sorry, that link is confusing. Correct link is: https://api.producthunt.com/v1/docs

**Comment by Vellieuxc** [comment]
Hi,
thank you for your answer!
The point is that I don't understand how to generate a token:
* The link API Dashboard is leading to this error message
* The request v1/oauth/token with the appropriate 3 headers
is leading to:
 {
  "status": "404",
  "error": "Not Found"
}

Thanks,
Clement

**Comment by andreasklinger** [comment]
The easiest way is to use the developer token you can generate in your api dashboard
otherwise you can follow this tutorial
https://api.producthunt.com/v1/docs/oauth_user_authentication/oauth_authorize_ask_for_access_grant_code_on_behalf_of_the_user

closing this for now - feel free to reopen with follow up questions
